In [1]:
import  numpy as np

#Creating Arrays from Python ListsFirst, we can use np.array to create arrays from Python lists:

In [2]:
#integer array
np.array([1,2,4,5,6])

array([1, 2, 4, 5, 6])

Remember that unlike Python lists, NumPy is constrained to 
arrays that all contain the same type. If types do not match, NumPy will upcast if possible
(here, integers are upcast to floating point):

In [3]:
np.array([3.14,5,6,3,2])

array([3.14, 5.  , 6.  , 3.  , 2.  ])

If we want to explicitly set the data type of the resulting array, we can use the dtype keyword:

In [4]:
np.array([1,2,3,4],dtype='float32')

array([1., 2., 3., 4.], dtype=float32)

Finally, unlike Python lists, NumPy arrays can explicitly be multidimensional; here’s one way of initializing a multidimensional array using a list of lists:

In [5]:
#nested list results in multidimensional arrays
np.array([range(i,i+3) for i in [2,4,6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

The inner lists are treated as rows of the resulting two-dimensional array.

# Creating Arrays from Scratch

Especially for larger arrays, it is more efficient to create arrays from scratch using routines built into NumPy. Here are several examples:

In [7]:
#Creating a length - 10 array filled with zeros
np.zeros(10,dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [8]:
#Create a 3X5 floating point array filled with ones
np.ones((3,5),dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [10]:
#Create a 3X5 array filled with 3.14
np.full((3,5),3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [11]:
#Create an array filled with linear sequence
#Starting at 0, ending at 20, stepping by 2
#(this is similar to tyhe built-in range() function)
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [12]:
#Create an array of five values evenly spaced between 0 and 1
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [13]:
#Create a 3X3 array uniformly distributed 
#random values between 0 and 1
np.random.random((3,3))

array([[0.92204633, 0.00302072, 0.19833742],
       [0.81568047, 0.0470429 , 0.83918835],
       [0.86246128, 0.68853679, 0.41666217]])

In [18]:
#Create a 3X3 array normally distributed random values
# with mean 0 and SD 1
np.random.normal(0,1,(3,3))

array([[ 1.65310489, -0.48565425, -1.05486749],
       [ 2.70736072, -0.54070881,  1.00015191],
       [ 0.21805338,  0.1510963 ,  1.27979602]])

In [20]:
#Create a 3X3 array of random integer in the interval (0,10)
np.random.randint(0,10,(3,3))

array([[1, 7, 5],
       [0, 9, 8],
       [7, 4, 5]])

In [22]:
#Create an 3X3 identity mtrix
np.eye(3)


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [24]:
#Create an unitialised array of three integer
#The values will be whatever existed at that 
#memory location

np.empty(3)


array([1., 1., 1.])

# NumPy Standard Data Types

NumPy arrays contain values of a single type, so it is important tohave detailed knowledge of those types and their limitations. BecauseNumPy is built in C, the types will be familiar to users of C, Fortran,and other related languages.

In [25]:
np.zeros(10, dtype='int16')

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int16)

Or using the associated NumPy object:

In [26]:
np.zeros(10, dtype=np.int16)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int16)

### The Basics of NumPy Arrays

Data manipulation in Python is nearly synonymous with NumPy array manipulation: even newer tools like Pandas (Chapter 3) are built around the NumPy array. This section will present several examples using NumPy array manipulation to access data and subarrays, and to split, reshape, and join the arrays. While the types of operations shown here may seem a bit dry and pedantic, they comprise the building blocks of many other examples used throughout the book. Get to know them well!

We’ll cover a few categories of basic array manipulations here:

Attributes of arrays

    Determining the size, shape, memory consumption, and data types of arrays
Indexing of arrays

    Getting and setting the value of individual array elements
Slicing of arrays

    Getting and setting smaller subarrays within a larger array
Reshaping of arrays

    Changing the shape of a given array
Joining and splitting of arrays

    Combining multiple arrays into one, and splitting one array into many


### NumPy Array Attributes

First let’s discuss some useful array attributes. We’ll start bydefining three random arrays: a one-dimensional, two-dimensional, andthree-dimensional array. We’ll use NumPy’s random number generator, which wewill seed with a set value in order to ensure that the same random arrays are generated each time this code is run:

In [29]:
import numpy as np
np.random.seed(0) #seed for reproducibility

x1 = np.random.randint(10, size=6) #one dimentional array

x2 = np.random.randint(10, size=(3,4))

x3 = np.random.randint(10, size=(3,4,5))

Each array has attributes ndim (the number of dimensions),shape (the size of each dimension), and size (the total size of the array):

In [31]:
print("x3 ndim:", x3.ndim)

print("x3 shape:", x3.shape)

print("x3 size:", x3.size)

x3 ndim: 3
x3 shape: (3, 4, 5)
x3 size: 60


Another useful attribute is the dtype, the data type of thearray 

In [32]:
print("x3 dtype:", x3.dtype)

x3 dtype: int64


Other attributes include itemsize, which lists the size (in bytes) ofeach array element, and nbytes, which lists the total size (in bytes)of the array:

In [33]:
print("itemsize:" , x3.itemsize, "bytes")

print("nbytes:", x3.nbytes, "bytes")

itemsize: 8 bytes
nbytes: 480 bytes


In general, we expect that nbytes is equal to itemsize times size.

#### Array Indexing: Accessing Single Elements

If you are familiar with Python’s standard list indexing, indexing in NumPy will feel quite familiar. In a one-dimensional array, you can access the ith value (counting from zero) by specifying the desired index in square brackets, just as with Python lists:

In [34]:
x1

array([5, 0, 3, 3, 7, 9])

In [35]:
x1[0]

5

In [36]:
x1[4]

7

To index from the end of the array, you can use negative indices:

In [37]:
x1[-1]

9

In [38]:
x1[-2]

7

In a multidimensional array, you access items using a comma-separated tuple of indices:

In [39]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [40]:
x2[0,0]

3

In [41]:
x2[2,0]

1

In [42]:
x2[2,-1]

7

You can also modify values using any of the above index notation:

In [44]:
x2[0,0] = 12
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

Keep in mind that, unlike Python lists, NumPy arrays have a fixed type.This means, for example, that if you attempt to insert a floating-pointvalue to an integer array, the value will be silently truncated. Don’t be caught unaware by this behavior!

In [45]:
x1[0] = 3.14159 # this will be truncated!
x1

array([3, 0, 3, 3, 7, 9])

#### Array Slicing: Accessing Subarrays

Just as we can use square brackets to access individual array elements,we can also use them to access subarrays with the slice notation,marked by the colon (:) character. The NumPy slicing syntax followsthat of the standard Python list; to access a slice of an array x, use this:

x[start:stop:step]

If any of these are unspecified, they default to the values start=0,stop=size of dimension, step=1. We’ll take a look at accessing subarrays in one dimension and in multiple dimensions.

### One-dimensional subarrays

In [47]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [48]:
x[:5] # first five elements

array([0, 1, 2, 3, 4])

In [49]:
x[5:] #element after index 5

array([5, 6, 7, 8, 9])

In [50]:
x[4:7] # middle subarray

array([4, 5, 6])

In [51]:
x[::2] #every other element

array([0, 2, 4, 6, 8])

In [52]:
x[1::2] # every other element starting index 1 

array([1, 3, 5, 7, 9])

A potentially confusing case is when the step value is negative. Inthis case, the defaults for start and stop are swapped. This becomesa convenient way to reverse an array:

In [53]:
x[::-1] #all element reversed 

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [54]:
x[5::-2] # reversed evert other from index 5

array([5, 3, 1])

#### MULTIDIMENSIONAL SUBARRAYS

Multidimensional slices work in the same way, with multiple slicesseparated by commas. For example:

In [57]:
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [58]:
x2[:2, :3] # two rows, three columns

array([[12,  5,  2],
       [ 7,  6,  8]])

In [59]:
x2[:3 , ::2] # all rows , every other columns

array([[12,  2],
       [ 7,  8],
       [ 1,  7]])

Finally, subarray dimensions can even be reversed together:

In [60]:
x2[::-1 ,::-1]

array([[ 7,  7,  6,  1],
       [ 8,  8,  6,  7],
       [ 4,  2,  5, 12]])


Accessing array rows and columns

One commonly needed routine is accessing single rows or columns of an array. You can do this by combining indexing and slicing, using an empty slice marked by a single colon (:):

In [61]:
print(x2[:, 0]) # first column of x2

[12  7  1]


In [62]:
print(x2[0, :])  # first row of x2

[12  5  2  4]


In the case of row access, the empty slice can be omitted for a more compact syntax:

In [63]:
print(x2[0]) # equivalent to x2[0, :]

[12  5  2  4]


### Subarrays as no-copy views

One important—and extremely useful—thing to know about array slicesis that they return views rather than copies of the array data. Thisis one area in which NumPy array slicing differs from Python listslicing: in lists, slices will be copies. Consider our two-dimensional array from before:

In [64]:
print(x2)

[[12  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


Let’s extract a 2×2 subarray from this:

In [66]:
x2_sub = x2[:2, :2]
print(x2_sub)

[[12  5]
 [ 7  6]]


Now if we modify this subarray, we’ll see that the original array is changed! Observe:

In [67]:
print(x2)

[[12  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


Let’s extract a 2×2 subarray from this:

In [68]:
x2_sub = x2[:2, :2]
print(x2_sub)

[[12  5]
 [ 7  6]]


Now if we modify this subarray, we’ll see that the original array is changed! Observe:

In [69]:
x2_sub[0, 0] = 99
print(x2_sub)

[[99  5]
 [ 7  6]]


In [70]:
print(x2)

[[99  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


This default behavior is actually quite useful: it means that when we work with large datasets, we can access and process pieces of these datasets without the need to copy the underlying data buffer.

### Creating copies of arrays

Despite the nice features of array views, it is sometimes useful to instead explicitly copy the data within an array or a subarray. This can be most easily done with the copy() method:

In [71]:
x2_sub_copy = x2[:2, :2].copy()

print(x2_sub_copy)

[[99  5]
 [ 7  6]]


If we now modify this subarray, the original array is not touched:

In [73]:
x2_sub_copy[0, 0] = 42
print(x2_sub_copy)

[[42  5]
 [ 7  6]]


In [74]:
print(x2)

[[99  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


### Reshaping of Arrays

Another useful type of operation is reshaping of arrays. The most flexible way of doing this is with the reshape() method. For example, if you want to put the numbers 1 through 9 in a 3×3 grid, you can do the following:

In [76]:
grid = np.arange(1,10).reshape(3,3)
print(grid)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


Note that for this to work, the size of the initial array must match the size of the reshaped array. Where possible, the reshape method will use a no-copy view of the initial array, but with noncontiguous memory buffers this is not always the case.

Another common reshaping pattern is the conversion of a one-dimensional array into a two-dimensional row or column matrix. You can do this with the reshape method, or more easily by making use of the newaxis keyword within a slice operation:

In [78]:
x = np.array([1,2,3])

#row vector via reshape
x.reshape((1,3))

array([[1, 2, 3]])

In [79]:
#row vector via newaxis
x[np.newaxis, :]

array([[1, 2, 3]])

In [80]:
# column vector via reshape
x.reshape((3,1))

array([[1],
       [2],
       [3]])

In [81]:
# column vector via newaxis
x[:, np.newaxis]

array([[1],
       [2],
       [3]])

We will see this type of transformation often throughout the remainder of the article.

### Array Concatenation and Splitting

All of the preceding routines worked on single arrays. It’s also possible tocombine multiple arrays into one, and to conversely split a single arrayinto multiple arrays. We’ll take a look at those operations here.

#### CONCATENATION OF ARRAYS

Concatenation, or joining of two arrays in NumPy, is primarily accomplished through the routines np.concatenate, np.vstack, and np.hstack. np.concatenate takes a tuple or list of arrays as its first argument, as we can see here:

In [84]:
x = np.array([1,2,3])
y = np.array([3,2,1])
np.concatenate([x,y])

array([1, 2, 3, 3, 2, 1])

You can also concatenate more than two arrays at once:

In [85]:
z = [99,99,99]
print(np.concatenate([x,y,z]))

[ 1  2  3  3  2  1 99 99 99]


np.concatenate can also be used for two-dimensional arrays:

In [87]:
grid = np.array([[1,2,3],[4,5,6]])


In [88]:
#concatenate along the first axis
np.concatenate([grid,grid])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [89]:
# concatenate along the second axis (zero indexed)
np.concatenate([grid, grid], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

For working with arrays of mixed dimensions, it can be clearer to use the np.vstack (vertical stack) and np.hstack (horizontal stack) functions

In [91]:
x = np.array([1,2,3])
grid = np.array([[9,8,7],[6,5,4]])

#vertically stack the arrays
np.vstack([x,grid])

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [92]:
# hortically stack the arrays
y = np.array([[99],[99]])
np.hstack([grid,y])

array([[ 9,  8,  7, 99],
       [ 6,  5,  4, 99]])

Similarly, np.dstack will stack arrays along the third axis.

#### SPLITTING OF ARRAY

The opposite of concatenation is splitting, which is implemented by the functions np.split, np.hsplit, and np.vsplit. For each of these, we can pass a list of indices giving the split points:

In [95]:
x = [1,2,3,99,99,3,2,1]

x1, x2, x3 = np.split(x,[3,5])

print(x1, x2, x3)

[1 2 3] [99 99] [3 2 1]


Notice that N split points lead to N + 1 subarrays. The related functions np.hsplit and np.vsplit are similar:

In [96]:
grid = np.arange(16).reshape((4,4))

grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [97]:
upper , lower = np.vsplit(grid, [2])
print(upper)
print(lower)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


In [98]:
left, right = np.hsplit(grid, [2])
print(left)
print(right)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


Similarly, np.dsplit will split arrays along the third axis.

### Computation on NumPy Arrays: Universal Functions

Up until now, we have been discussing some of the basic nuts and bolts of NumPy; in the next few sections, we will dive into the reasons that NumPy is so important in the Python data science world. Namely, it provides an easy and flexible interface to optimized computation with arrays of data.

Computation on NumPy arrays can be very fast, or it can be very slow. The key to making it fast is to use vectorized operations, generally implemented through NumPy’s universal functions (ufuncs). This section motivates the need for NumPy’s ufuncs, which can be used to make repeated calculations on array elements much more efficient. It then introduces many of the most common and useful arithmetic ufuncs available in the NumPy package.

##### The Slowness of Loops

Python’s default implementation (known as CPython) does some operations very slowly. This is in part due to the dynamic, interpreted nature of the language: the fact that types are flexible, so that sequences of operations cannot be compiled down to efficient machine code as in languages like C and Fortran. Recently there have been various attempts to address this weakness: well-known examples are the PyPy project, a just-in-time compiled implementation of Python; the Cython project, which converts Python code to compilable C code; and the Numba project, which converts snippets of Python code to fast LLVM bytecode. Each of these has its strengths and weaknesses, but it is safe to say that none of the three approaches has yet surpassed the reach and popularity of the standard CPython engine.

The relative sluggishness of Python generally manifests itself in situations where many small operations are being repeated—for instance, looping over arrays to operate on each element. For example, imagine we have an array of values and we’d like to compute the reciprocal of each. A straightforward approach might look like this:

In [99]:
import numpy as np
np.random.seed(0)

def compute_reciprocals(values):
    output = np.empty(len(values))
    for i in range(len(values)):
        output[i] = 1/values[i]
    return output

values = np.random.randint(1,10,size=5)
compute_reciprocals(values)

array([0.16666667, 1.        , 0.25      , 0.25      , 0.125     ])